### ISSUE TITLE
Field loop advection

### ISSUE THREAD

**Issue by changgoo** [pmocz/constrainedtransport-python#1]
Hey! I really enjoy your python coding tutorials! 

I was intrigued by the CT example you presented, which is basically the arithmetic averaging method presented in [Gardiner & Stone (2005)](https://ui.adsabs.harvard.edu/abs/2005JCoPh.205..509G/abstract). Recently, I have had a chance to think about the CT method a bit deeper, so I did the field loop advection test using your script! 

https://github.com/changgoo/constrainedtransport-python/tree/field_loop

The final outcome can be compared with Figure 3 in GS05 (top right). Surprisingly, it worked better than I expected! My interpretation is that it is due to the diffusive LLF flux you've used, but not sure. Perhaps, I may try the EMF-alpha and EMF-c they suggested as well as more formal UCT algorithm in [Mignone & Del Zanna (2021)](https://ui.adsabs.harvard.edu/abs/2021JCoPh.42409748M/abstract).

**Comment by changgoo** [comment]
Ah, maybe I'm wrong. Since you used the LLF fluxes of B for EMF, it is actually the EMF-alpha method (i.e., top left of Figure 3 in GS05).

**Comment by pmocz** [comment]
That's really awesome Chang-Goo! I'm excited that you modified the scheme. 

The method is based off the flux-CT scheme of Toth (2000): https://www.sciencedirect.com/science/article/abs/pii/S0021999100965197

or, at least my variant of it (Mocz 2017), if you consider how the hydro is solved: https://www.sciencedirect.com/science/article/abs/pii/S0021999116304806?via%3Dihub

I'm glad to see the method performed alright on the advection of field loop test. I'll have to try it with an HLLD solver and see if it works or needs some upwind corrections in that case

**Comment by changgoo** [comment]
Okay, so this is basically the flux-CT from Balsara and Spicer? Then, I think my question still stays. The original claim in GS05 is that the original flux-CT using arithmetic averaging doesn't reduce to 1D grid-aligned flow. In this case, they demonstrated that the original flux-CT doesn't behave well for the field loop advection test, which is not the case in your scheme. So, it is still confusing to me!

**Comment by ltlancas** [comment]
Hi Philip and Chang-Goo! I've been thinking a good bit about CT algorithm's lately and Chang-Goo pointed this out to me, really cool Philip! On Chang-Goo's point, I would think that the LLF flux for the hydro variables could be causing the filed advection loop test to be less oscillatory. Do you think that's what's going on?

**Comment by pmocz** [comment]
I suspect its the use of the LFF flux as well!

**Comment by pmocz** [comment]
I wanted to share a figure of the advection field loop test that compared the methods I implemented in my 2017 paper (which used HLLD): https://www.sciencedirect.com/science/article/abs/pii/S0021999116304806?via%3Dihub

![image](https://user-images.githubusercontent.com/7489877/233290499-43af307c-ba99-4854-b944-fbc6b8353afc.png)
