### ISSUE TITLE
3D implementation

### ISSUE THREAD

**Issue by loliverhennigh** [pmocz/constrainedtransport-python#2]
Feel free to remove this Philip issue but extended this to 3D with JAX here, https://github.com/loliverhennigh/ConstrainedTransportZPinch?tab=readme-ov-file. 

Took me a while to figure out how to do some of the flux and time step equations in 3D so figured it might help others.

**Comment by pmocz** [comment]
This is incredible! I'm so excited to see the code extended to JAX and 3D
