### ISSUE TITLE
Possible error with applyFluxes function

### ISSUE THREAD

**Issue by Altius01** [pmocz/constrainedtransport-python#3]
In apllyFluxes function in the divergence of the fluxes calculation the right and left face fluxes difference multiplies by "dx", whereas in this case it is necessary to divide.
```python
    def applyFluxes(F, flux_F_X, flux_F_Y, dx, dt):
      R = -1  # right
      L = 1  # left
  
      # update solution
      F += -dt * dx * flux_F_X
      F += dt * dx * np.roll(flux_F_X, L, axis=0)
      F += -dt * dx * flux_F_Y
      F += dt * dx * np.roll(flux_F_Y, L, axis=1)

**Comment by pmocz** [comment]
The code as written is correct. The update should look like:

conserved_variable += timestep * area_of_face * flux

The area of the face is `dx` in a 2D simulation

**Comment by Altius01** [comment]
Oh, sorry, Ive forgot about integration in second dimension.
Thanks for your answer!
